Update capital_of prop
whosonfirst/whosonfirst-properties pull request #102
Opened 2020-12-08 18:34 UTC by stepps00

This PR updates the property `type` for `wof:capital_of` from string to list. This is needed to better represent the relationships between capitals and countries/admin1 records in WOF.

2020-12-08 19:04 UTC, nvkelso requested changes

2020-12-08 19:04 UTC, nvkelso commented on properties/wof/capital_of.json
>      "description": "A string property used to link administrative, judicial, and/or legislative capitals to their parent country or dependency. The values are equal to the wof:id of the parent countr
Please also update the `description` to indicate it's a list of WOF IDs, and that it is for any placetype (including `region` and `county`), though it's only commonly filled out for `country` and `dependency`.

2020-12-08 19:24 UTC, stepps00 commented on properties/wof/capital_of.json
>      "description": "A string property used to link administrative, judicial, and/or legislative capitals to their parent country or dependency. The values are equal to the wof:id of the parent countr
I updated the property description in a0fa80f.

2020-12-08 19:33 UTC, nvkelso requested changes

2020-12-08 19:33 UTC, nvkelso commented on properties/wof/README.md
> +A list property used to link administrative, judicial, and/or legislative capitals to their parent administrative record. The values are equal to the `wof:id` of each parent administrative record. Th
to:
`of the parent administrative records it is capital of`?

from:
`of each parent administrative record`

2020-12-08 19:51 UTC, stepps00 commented on properties/wof/README.md
> +A list property used to link administrative, judicial, and/or legislative capitals to their parent administrative record. The values are equal to the `wof:id` of each parent administrative record. Th
Agree this is a clearer description. Updated in 7410e7c.

2020-12-09 17:56 UTC, nvkelso approved these changes

2020-12-09 20:21 UTC, merged