Add new wof concordances x official property
whosonfirst/whosonfirst-properties pull request #113
Opened 2023-09-19 18:28 UTC by nvkelso

Also updates the list of most common concordance keys

2023-09-19 18:31 UTC, nvkelso commented
I should regenerate the Markdown, but the Makefile is throwing an error. I'll investigate...

2023-09-20 15:52 UTC, stepps00 requested changes

2023-09-20 15:52 UTC, stepps00 commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
If more, are those stored in a `wof:concordances_x_offical_alt` property? Or are we assuming one key per source / multiple sources possible in this `wof:concordances_x_offical` property?

2023-09-20 15:54 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
Great feedback, I'll revise.

2023-09-20 16:14 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
So far I've seen 1 example where there are 2 different official IDs in a country. France has `fra-insee:code` (default)
and `frgov:epci_code` (alt) for communes, because they sometimes group together into a type of regional federation.

Generally I think the "census" / "statistical" IDs should be given priority for the default official value – less so the GIS unique feature IDs from the national mapping agency (which are more like FIDs either numerical or GUIDs and I've generally avoided adding as they are rare and not useful for demographic data joins, you'll see the GUID type IDs in the United Kingdom). 

Sometimes I've also researched a "qualified" code in addition to the basic code. In Spain: `esp-ine:code` (default) and `esp-ine:code_qualified` where it includes the parent's national ID code as a prefix, which is more how we'd expect things in the US but not always how data is published elsewhere. NOTE: Poland is an exception in that I couldn't figure out what the basic could would be:`pol-gus:terc_code_qualified`.

There are other example where a regional body like EuroGeographics will set a multicountry ID (mostly by prefixing the country code and a _ separator) onto the national ID. So those could also go into an "alt" listing.

+1 to also allowing for `wof:concordances_x_offical_alt` as a list of string values, I'll add a definition. 

Since the default should just be a single value, then I'll modify `wof:concordances_x_offical` to be a string. That'll better match how `wof:concordances` (versus how I originally patterned the data structure off `name:*`).

2023-09-20 16:52 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
@stepps00 take another look now that https://github.com/whosonfirst/whosonfirst-properties/pull/113/commits/8ae956b735684fca2f41ec40be6302c7cf500655 landed?

2023-09-20 17:45 UTC, thisisaaronland commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
Maybe `wof:concordances_x_offical` is a list and `wof:concordances_x_preferred` (or `wof:concordances_x_official_preferred`) is a singleton?

2023-09-20 18:11 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
Great ideas! Let me list them out so we can compare in one place...

If we wanted to match how `name:*` and `label:*` properties are named, then:

- `wof:concordances_x_preferred_official` as a singleton
    - NOTE: this is anti pattern to single element lists elsewhere in `name:*` and `label:*` but that's OK?
    - QUESTION: Should this be plural or singular (eg drop the `s` to `wof:concordance_x_preferred_official`). Because the variant form would be plural, I think this should be plural? And if it's plural than should it be a single element list? 🤯 
- `wof:concordances_x_variant_official` as a list
    - QUESTION: Should this be plural or singular (eg drop the `s` to `wof:concordance_x_variant_official`). It's a list, so probably plural is better?

Mashup option: That swaps the order around from the earlier draft (which was a mashup between concordance and label), where `official` is at the end rather than the middle:

- `wof:concordances_x_official_preferred` as a singleton
- `wof:concordances_x_offical_variant` as a list

If we matched how `wof:concordances` and `wof:concordances_alt` properties are named, then:

- `wof:concordances_x_official` as a singleton
- `wof:concordances_x_offical_alt` as a list

I'm also open to another term besides `official` if someone has one...

2023-09-20 22:05 UTC, thisisaaronland commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
Removing the `_x_` would distinguish it from the `name:` and `label:` properties which are the way they are because they are meant to conform to (or at least follow) BCP47 convention.

Given that we already have a whole series of `_SOMETHING` properties it seems fine to just remove the `_x_`.

I am trying to imagine a scenario where concordance identifiers might be scoped to language which seems absurd on the face of it but that's never stopped people in the past. I think this is fine (and maps to what we already do with placetypes):

* `wof:concordances_official`
* `wof:concordances_official_alt`

2023-09-20 23:15 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
> I am trying to imagine a scenario where concordance identifiers might be scoped to language which seems absurd on the face of it but that's never stopped people in the past. I think this is fine (and maps to what we already do with placetypes):

The only extreme case I've run across is from Transit where the `ref` on a transit line is numerical but in a different character set then Arabic numerals common in most Latin and non-Latin languages, and it's appropriate to add a `ref:en` to get a localized value. But I think that's less a unique identifier "concordance" and more a type of "label" where we in WOF already support localization.

So for final approval:

- `wof:concordances_official` as a singleton string value
- `wof:concordances_official_alt` as a list of string values

To confirm that the `wof:concordances_official` is a singleton string value (not a list of string values).

2023-09-20 23:20 UTC, nvkelso commented on properties/wof/concordances_x_official.json
> +    "description": "One or more concordance keys. These represent the concordance key(s) for officially recognized identifiers for the sources of the corresponding WOF record.",
PR has been updated to reflect latest state of play via https://github.com/whosonfirst/whosonfirst-properties/pull/113/commits/caa521fbd502a35e3c50acff10d01a5a1c285e34 and https://github.com/whosonfirst/whosonfirst-properties/pull/113/commits/b80968a71de53fe574596cfce49a2fdf8639f480.

2023-09-21 03:36 UTC, stepps00 commented on properties/wof/concordances.json
> +        "no-geonorge:kommunenum": {
spot checked, this is correct.

2023-09-21 03:38 UTC, stepps00 commented on properties/wof/concordances.json
> +        "eg:gisco_id": {
https://spelunker.whosonfirst.org/id/1713305773/

spot checked, looks good.

2023-09-21 03:39 UTC, stepps00 commented on properties/wof/concordances.json
> +        "ee-mamt:code": {
I see WOF also uses okood from this source, too?

https://spelunker.whosonfirst.org/id/1713305773/

Probably ok, just calling it out.

2023-09-21 03:40 UTC, stepps00 approved these changes
A few comments about the codes listed in the concordances file, but LGTM otherwise

2023-09-27 19:18 UTC, nvkelso commented on properties/wof/concordances.json
> +        "ee-mamt:code": {
Good catch! I've revised to `okood` since that's the existing thing we do.

Generally for new concordance key IDs I set it to English translation of the value.

2023-09-27 20:44 UTC, nvkelso commented on properties/wof/concordances.json
> +        "no-geonorge:kommunenum": {
Switched to `no-geonorge:number` so this key can be used for more than one placetype in Norway.

2023-09-27 20:44 UTC, nvkelso commented on properties/wof/concordances.json
> +        "ee-mamt:code": {
Fixed via https://github.com/whosonfirst/whosonfirst-properties/pull/113/commits/9a50ba5beb85203b51b30f1420b4a4560ec5173b.

2023-09-27 20:54 UTC, merged